name: mp_chart
description: A starting point for Dart libraries or applications.

publish_to: none

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  matrix4_transform: ^2.0.0


  # optimized_gesture_detector:
  #   path: ../../OptimizedGestureDetector

  optimized_gesture_detector:
    git:
        url: git@github.com:Tip-Off/OptimizedGestureDetector.git
        ref: master

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
