name: mp_chart
description: A starting point for Dart libraries or applications.

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  optimized_gesture_detector:
    path: ../../OptimizedGestureDetector

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
